[source_photoz_u]
u_0_uncorr = gaussian 0.0 1.0
u_1_uncorr = gaussian 0.0 1.0
u_2_uncorr = gaussian 0.0 1.0
u_3_uncorr = gaussian 0.0 1.0
u_4_uncorr = gaussian 0.0 1.0
u_5_uncorr = gaussian 0.0 1.0
u_6_uncorr = gaussian 0.0 1.0
;u_7_uncorr = gaussian 0.0 1.0
;u_8_uncorr = gaussian 0.0 1.0

[shear_calibration_parameters]
; m1 = gaussian 0.0 0.0091
; m2 = gaussian 0.0 0.0078
; m3 = gaussian 0.0 0.0076
; m4 = gaussian 0.0 0.0076
; nzmode parameters. If nz mode parameters are not varied, 
; those are not used. 
m1_uncorr = gaussian 0.0 1.0
m2_uncorr = gaussian 0.0 1.0
m3_uncorr = gaussian 0.0 1.0
m4_uncorr = gaussian 0.0 1.0