[source_photoz_u]
u_0_uncorr = -3.0 0.0 3.0
u_1_uncorr = -3.0 0.0 3.0
u_2_uncorr = -3.0 0.0 3.0
u_3_uncorr = -3.0 0.0 3.0
u_4_uncorr = -3.0 0.0 3.0
u_5_uncorr = -3.0 0.0 3.0
u_6_uncorr = -3.0 0.0 3.0
;u_7_uncorr = -3.0 0.0 3.0
;u_8_uncorr = -3.0 0.0 3.0