; LCDM
; 3x2pt without 2nd lens bin
; Sum of neutrino masses fixed to 0.06 eV
; Nonlinear P(k) computed with baryonic feedback version of HMcode 2020
; with baryonic feedback fixing T_AGN=7.7
; NLA IA model w 2 params (amplitude and z power law)
; Gaussian priors on magnification using Y6 Balrog priors for DV 5.1
; nzmode redshift calibration
; Linear galaxy bias (default if no galbias noted)

[DEFAULT]
2pt_file=/global/homes/j/joaovsr/y6kp-extensions//data_vectors/3x2pt_2025-07-28-20h_UNBLINDED_wmask_nob2.fits   
sr_file=/global/homes/j/joaovsr/y6kp-extensions//data_vectors/sim_d-gen2pt_simy6_l-desy3-hm20-tatt_ml6_sy3_sr.npy   
sr_module=${SR_MODULE}   
action_consistency=consistency bbn_consistency   
action_camb=camb   
action_postpk=   
action_6x2pt=   
action_postlike=desi_bao   
action_preboltzmann=   
action_nubias=   
action_marg_nz=correlated_priors photoz_uz_lens photoz_uz_source   
action_xlens=   
2pt_data_sets=xip xim gammat wtheta   
ini_run_name=lcdm_datavector_run
long_run_name=lcdm_datavector_run
orig_ebossdir=/global/homes/j/joaovsr/cosmosis-standard-library/likelihood/eboss_dr16   
root=/global/homes/j/joaovsr/cosmosis-standard-library   

[runtime]
verbosity  	 = 	 silent  
sampler    	 = 	 test  

[output]
filename   	 = 	 ${OUTPUT_DIR}/lcdm_datavector_run.txt
format     	 = 	 text  
lock       	 = 	 T  
privacy    	 = 	 F  

[pipeline]
modules    	 = 	 w0wa_check consistency bbn_consistency  camb  fast_pt fits_nz correlated_priors photoz_uz_lens photoz_uz_source IA pk_to_cl_gg pk_to_cl add_magnification  add_intrinsic 2pt_shear 2pt_gal 2pt_gal_shear shear_m_bias add_point_mass 2pt_like
timing     	 = 	 T
priors     	 = 	 /global/homes/j/joaovsr/y6_code_comparison/cosmosis/ini/lcdm/priors.ini 
values     	 = 	 /global/homes/j/joaovsr/y6_code_comparison/cosmosis/ini/lcdm/values.ini 
extra_output 	 = 	 cosmological_parameters/sigma_8 cosmological_parameters/sigma_12 data_vector/2pt_chi2
fast_slow  	 = 	 F  

[test]
save_dir   	 = 	 /global/homes/j/joaovsr/y6_code_comparison/cosmosis/lcdm_datavector_run

[w0wa_check]
file       	 = 	 utility/exclude_w0_wa/w0wa_sum_prior.py  

[consistency]
file       	 = 	 utility/consistency/consistency_interface.py  

[bbn_consistency]
file       	 = 	 utility/bbn_consistency/bbn_consistency.py  

[camb]
file       	 = 	 boltzmann/camb/camb_interface.py  
mode       	 = 	 power  
lmax       	 = 	 2500  
feedback   	 = 	 0  
accuracyboost 	 = 	 1 # bring this back to 1.1
do_tensors 	 = 	 T  
do_lensing 	 = 	 T  
nonlinear  	 = 	 pk  
halofit_version 	 = 	 mead2020_feedback  
zmin_background 	 = 	 0.  
zmax_background 	 = 	 4.  
nz_background 	 = 	 401  
kmin       	 = 	 1e-4  
kmax       	 = 	 10.0  
kmax_extrapolate 	 = 	 500.0  
nk         	 = 	 400  
zmin       	 = 	 0.0  
zmax       	 = 	 4.0  
nz         	 = 	 150  

[fast_pt]
file       	 = 	 structure/fast_pt/fast_pt_interface.py  
do_ia      	 = 	 T
k_res_fac  	 = 	 0.5  
verbose    	 = 	 F  

[fits_nz]
file       	 = 	 number_density/load_nz_fits/load_nz_fits.py  
nz_file    	 = 	 /global/homes/j/joaovsr/y6kp-extensions//data_vectors/3x2pt_2025-07-28-20h_UNBLINDED_wmask_nob2.fits  
data_sets  	 = 	 lens source  
prefix_section 	 = 	 T  
prefix_extension 	 = 	 T  

[correlated_priors]
file       	 = 	 number_density/correlated_priors/correlated_priors.py  
uncorrelated_parameters 	 = 	 shear_calibration_parameters/m1_uncorr shear_calibration_parameters/m2_uncorr shear_calibration_parameters/m3_uncorr shear_calibration_parameters/m4_uncorr source_photoz_u/u_0_uncorr source_photoz_u/u_1_uncorr source_photoz_u/u_2_uncorr source_photoz_u/u_3_uncorr source_photoz_u/u_4_uncorr source_photoz_u/u_5_uncorr source_photoz_u/u_6_uncorr  
output_parameters 	 = 	 shear_calibration_parameters/m1 shear_calibration_parameters/m2 shear_calibration_parameters/m3 shear_calibration_parameters/m4 source_photoz_u/u_0 source_photoz_u/u_1 source_photoz_u/u_2 source_photoz_u/u_3 source_photoz_u/u_4 source_photoz_u/u_5 source_photoz_u/u_6  
covariance 	 = 	 /global/homes/j/joaovsr/y6kp-extensions//inc_ini_nzmode/covmat_multigauss.asc  
mean       	 = 	 /global/homes/j/joaovsr/y6kp-extensions//inc_ini_nzmode/mean_multigauss.asc  

[photoz_uz_lens]
file       	 = 	 modules_desy6/photoz_uz/photoz_uz.py  
sample     	 = 	 lens  
basis_file 	 = 	 /global/homes/j/joaovsr/y6kp-extensions//inc_ini_nzmode/U_lens_sompzwz.npz  
n_modes    	 = 	 3  

[photoz_uz_source]
file       	 = 	 modules_desy6/photoz_uz/photoz_uz.py  
sample     	 = 	 source  
basis_file 	 = 	 /global/homes/j/joaovsr/y6kp-extensions//inc_ini_nzmode/U_source_v3d1.npz  
n_modes    	 = 	 7  

[IA]
file       	 = 	 intrinsic_alignments/tatt/tatt_interface.py
sub_lowk   	 = 	 F  
do_galaxy_intrinsic 	 = 	 F
ia_model   	 = 	 nla  

[pk_to_cl_gg]
file       	 = 	 structure/projection/project_2d.py  
lingal-lingal 	 = 	 lens-lens  
do_exact   	 = 	 lingal-lingal  
do_rsd     	 = 	 True  
ell_min_linspaced 	 = 	 1  
ell_max_linspaced 	 = 	 4  
n_ell_linspaced 	 = 	 5  
ell_min_logspaced 	 = 	 5.  
ell_max_logspaced 	 = 	 1.e5  
n_ell_logspaced 	 = 	 80  
limber_ell_start 	 = 	 200  
auto_only  	 = 	 lingal-lingal  
sig_over_dchi_exact 	 = 	 3.5  
verbose    	 = 	 F  

[pk_to_cl]
file       	 = 	 structure/projection/project_2d.py  
ell_min_logspaced 	 = 	 0.1  
ell_max_logspaced 	 = 	 5.0e5  
n_ell_logspaced 	 = 	 100  
shear-shear 	 = 	 source-source  
shear-intrinsic 	 = 	 source-source  
intrinsic-intrinsic 	 = 	 source-source  
intrinsicb-intrinsicb 	 = 	 source-source  
lingal-shear 	 = 	 lens-source  
lingal-intrinsic 	 = 	 lens-source  
lingal-magnification 	 = 	 lens-lens  
magnification-shear 	 = 	 lens-source  
magnification-magnification 	 = 	 lens-lens  
magnification-intrinsic 	 = 	 lens-source  
verbose    	 = 	 F  
get_kernel_peaks 	 = 	 F  
sig_over_dchi 	 = 	 20.  
shear_kernel_dchi 	 = 	 10.  

[add_magnification]
file       	 = 	 structure/magnification/add_magnification.py  
include_intrinsic 	 = 	 T  

[add_intrinsic]
file       	 = 	 shear/add_intrinsic/add_intrinsic.py  
shear-shear 	 = 	 T  
position-shear 	 = 	 T  
perbin     	 = 	 F  

[2pt_shear]
file       	 = 	 shear/cl_to_xi_fullsky/cl_to_xi_interface.py  
ell_max    	 = 	 40000  
xi_type    	 = 	 EB  
theta_file 	 = 	 /global/homes/j/joaovsr/y6kp-extensions//data_vectors/3x2pt_2025-07-28-20h_UNBLINDED_wmask_nob2.fits  
bin_avg    	 = 	 T  
input_section_name 	 = 	 shear_cl  shear_cl_bb  
output_section_name 	 = 	 shear_xi_plus  shear_xi_minus  

[2pt_gal]
file       	 = 	 shear/cl_to_xi_fullsky/cl_to_xi_interface.py  
ell_max    	 = 	 40000  
xi_type    	 = 	 '00'  
theta_file 	 = 	 /global/homes/j/joaovsr/y6kp-extensions//data_vectors/3x2pt_2025-07-28-20h_UNBLINDED_wmask_nob2.fits  
bin_avg    	 = 	 T  

[2pt_gal_shear]
file       	 = 	 shear/cl_to_xi_fullsky/cl_to_xi_interface.py  
ell_max    	 = 	 40000  
xi_type    	 = 	 '02'  
theta_file 	 = 	 /global/homes/j/joaovsr/y6kp-extensions//data_vectors/3x2pt_2025-07-28-20h_UNBLINDED_wmask_nob2.fits  
bin_avg    	 = 	 T  

[shear_m_bias]
file       	 = 	 shear/shear_bias/shear_m_bias.py  
m_per_bin  	 = 	 True  
cl_section 	 = 	 shear_xi_plus shear_xi_minus  
cross_section 	 = 	 galaxy_shear_xi  
verbose    	 = 	 F  

[add_point_mass]
file       	 = 	 shear/point_mass/add_gammat_point_mass.py  
add_togammat 	 = 	 False  
use_fiducial 	 = 	 True  
sigcrit_inv_section 	 = 	 sigma_crit_inv_lens_source  

[2pt_like]
file       	 = 	 likelihood/2pt/2pt_point_mass/2pt_point_mass.py  
do_pm_marg 	 = 	 True  
do_pm_sigcritinv 	 = 	 True  
sigma_a    	 = 	 10000.0  
no_det_fac 	 = 	 False  
include_norm 	 = 	 True  
data_file  	 = 	 /global/homes/j/joaovsr/y6kp-extensions//data_vectors/3x2pt_2025-07-28-20h_UNBLINDED_wmask_nob2.fits  
data_sets  	 = 	 xip xim gammat wtheta  
make_covariance 	 = 	 F  
covmat_name 	 = 	 COVMAT  
cut_wtheta 	 = 	 1,2 1,3 1,4 1,5 1,6 2,3 2,4 2,5 2,6 3,4 3,5 3,6 4,5 4,6 5,6  
angle_range_xip_1_1 	 = 	 2.9697 250.0000  
angle_range_xip_1_2 	 = 	 4.7066 250.0000  
angle_range_xip_1_3 	 = 	 7.4595 250.0000  
angle_range_xip_1_4 	 = 	 7.4595 250.0000  
angle_range_xip_2_2 	 = 	 4.7066 250.0000  
angle_range_xip_2_3 	 = 	 9.3910 250.0000  
angle_range_xip_2_4 	 = 	 9.3910 250.0000  
angle_range_xip_3_3 	 = 	 18.7374 250.0000  
angle_range_xip_3_4 	 = 	 29.6968 250.0000  
angle_range_xip_4_4 	 = 	 18.7374 250.0000  
angle_range_xim_1_1 	 = 	 23.5890 250.0000  
angle_range_xim_1_2 	 = 	 47.0663 250.0000  
angle_range_xim_1_3 	 = 	 74.5950 250.0000  
angle_range_xim_1_4 	 = 	 74.5950 250.0000  
angle_range_xim_2_2 	 = 	 47.0663 250.0000  
angle_range_xim_2_3 	 = 	 118.2251 250.0000  
angle_range_xim_2_4 	 = 	 118.2251 250.0000  
angle_range_xim_3_3 	 = 	 118.2251 250.0000  
angle_range_xim_3_4 	 = 	 148.8366 250.0000  
angle_range_xim_4_4 	 = 	 118.2251 250.0000  
angle_range_gammat_1_1 	 = 	 24.268 250.0  
angle_range_gammat_1_2 	 = 	 24.268 250.0  
angle_range_gammat_1_3 	 = 	 24.268 250.0  
angle_range_gammat_1_4 	 = 	 24.268 250.0  
angle_range_gammat_2_1 	 = 	 250.0 250.0  
angle_range_gammat_2_2 	 = 	 250.0 250.0  
angle_range_gammat_2_3 	 = 	 250.0 250.0  
angle_range_gammat_2_4 	 = 	 250.0 250.0  
angle_range_gammat_3_1 	 = 	 12.99 250.0  
angle_range_gammat_3_2 	 = 	 12.99 250.0  
angle_range_gammat_3_3 	 = 	 12.99 250.0  
angle_range_gammat_3_4 	 = 	 12.99 250.0  
angle_range_gammat_4_1 	 = 	 10.858 250.0  
angle_range_gammat_4_2 	 = 	 10.858 250.0  
angle_range_gammat_4_3 	 = 	 10.858 250.0  
angle_range_gammat_4_4 	 = 	 10.858 250.0  
angle_range_gammat_5_1 	 = 	 9.677 250.0  
angle_range_gammat_5_2 	 = 	 9.677 250.0  
angle_range_gammat_5_3 	 = 	 9.677 250.0  
angle_range_gammat_5_4 	 = 	 9.677 250.0  
angle_range_gammat_6_1 	 = 	 8.7000 250.0  
angle_range_gammat_6_2 	 = 	 8.7000 250.0  
angle_range_gammat_6_3 	 = 	 8.7000 250.0  
angle_range_gammat_6_4 	 = 	 8.7000 250.0  
angle_range_wtheta_1_1 	 = 	 36.402 250.0  
angle_range_wtheta_1_2 	 = 	 999.0000 999.0000  
angle_range_wtheta_1_3 	 = 	 999.0000 999.0000  
angle_range_wtheta_1_4 	 = 	 999.0000 999.0000  
angle_range_wtheta_1_5 	 = 	 999.0000 999.0000  
angle_range_wtheta_1_6 	 = 	 999.0000 999.0000  
angle_range_wtheta_2_2 	 = 	 250.0000 250.0000  
angle_range_wtheta_2_3 	 = 	 999.0000 999.0000  
angle_range_wtheta_2_4 	 = 	 999.0000 999.0000  
angle_range_wtheta_2_5 	 = 	 999.0000 999.0000  
angle_range_wtheta_2_6 	 = 	 999.0000 999.0000  
angle_range_wtheta_3_3 	 = 	 19.485 250.0  
angle_range_wtheta_3_4 	 = 	 999.0000 999.0000  
angle_range_wtheta_3_5 	 = 	 999.0000 999.0000  
angle_range_wtheta_3_6 	 = 	 999.0000 999.0000  
angle_range_wtheta_4_4 	 = 	 16.287 250.0  
angle_range_wtheta_4_5 	 = 	 999.0000 999.0000  
angle_range_wtheta_4_6 	 = 	 999.0000 999.0000  
angle_range_wtheta_5_5 	 = 	 14.515 250.0  
angle_range_wtheta_5_6 	 = 	 999.0000 999.0000  
angle_range_wtheta_6_6 	 = 	 13.322 250.0  

