;%include priors.ini
;%include inc_ini_3x2pt_data/priors_3x2pt_${LENS_TAG}_${SOURCE_TAG}.ini
;%include inc_ini_magnification/priors_y6bal2gauss_ml6.ini
;%include inc_ini_nzmode/priors_u_source.ini
;%include inc_ini_nzmode/priors_u_lens.ini


; 3x2pt without 2nd lens bin + DESI DR2 BAO
; LCDM
; Sum of neutrino masses fixed to 0.06 eV
; Nonlinear P(k) computed with baryonic feedback version of HMcode 2020
; NLA IA model w 2 params (amplitude and z power law)
; with baryonic feedback fixing T_AGN=7.7
; Gaussian priors on magnification using Y6 Balrog priors for DV 5.1
; nzmode redshift calibration
; Linear galaxy bias (default if no galbias noted)

[cosmological_parameters]

[mag_alpha_lens]
alpha_1    	 = 	 gaussian 1.58 0.04  
alpha_2    	 = 	 gaussian 1.38 0.11  
alpha_3    	 = 	 gaussian 2.04 0.08  
alpha_4    	 = 	 gaussian 2.21 0.08  
alpha_5    	 = 	 gaussian 2.45 0.14  
alpha_6    	 = 	 gaussian 2.42 0.13  

[source_photoz_u]
u_0_uncorr 	 = 	 gaussian 0.0 1.0  
u_1_uncorr 	 = 	 gaussian 0.0 1.0  
u_2_uncorr 	 = 	 gaussian 0.0 1.0  
u_3_uncorr 	 = 	 gaussian 0.0 1.0  
u_4_uncorr 	 = 	 gaussian 0.0 1.0  
u_5_uncorr 	 = 	 gaussian 0.0 1.0  
u_6_uncorr 	 = 	 gaussian 0.0 1.0  

[shear_calibration_parameters]
m1_uncorr  	 = 	 gaussian 0.0 1.0  
m2_uncorr  	 = 	 gaussian 0.0 1.0  
m3_uncorr  	 = 	 gaussian 0.0 1.0  
m4_uncorr  	 = 	 gaussian 0.0 1.0  

[lens_photoz_u]
u_0_0      	 = 	 gaussian 0.0 1.0  
u_0_1      	 = 	 gaussian 0.0 1.0  
u_0_2      	 = 	 gaussian 0.0 1.0  
u_1_0      	 = 	 gaussian 0.0 1.0  
u_1_1      	 = 	 gaussian 0.0 1.0  
u_1_2      	 = 	 gaussian 0.0 1.0  
u_2_0      	 = 	 gaussian 0.0 1.0  
u_2_1      	 = 	 gaussian 0.0 1.0  
u_2_2      	 = 	 gaussian 0.0 1.0  
u_3_0      	 = 	 gaussian 0.0 1.0  
u_3_1      	 = 	 gaussian 0.0 1.0  
u_3_2      	 = 	 gaussian 0.0 1.0  
u_4_0      	 = 	 gaussian 0.0 1.0  
u_4_1      	 = 	 gaussian 0.0 1.0  
u_4_2      	 = 	 gaussian 0.0 1.0  
u_5_0      	 = 	 gaussian 0.0 1.0  
u_5_1      	 = 	 gaussian 0.0 1.0  
u_5_2      	 = 	 gaussian 0.0 1.0  

