;%include inc_ini_cosmology/values_fid_cosmology.ini
;%include inc_ini_cosmology/values_fixmnu.ini
;%include inc_ini_3x2pt_data/values_3x2pt_${LENS_TAG}_${SOURCE_TAG}.ini
;%include inc_ini_3x2pt_data/values_3x2pt_${LENS_TAG}_${SOURCE_TAG}.ini
;%include inc_ini_baryons/values_TAGN_fix_7.7.ini
;%include inc_ini_magnification/values_y6bal2gauss_${LENS_TAG}.ini
;%include inc_ini_ia/values_nla.ini
;%include inc_ini_nzmode/values_u_source.ini
;%include inc_ini_nzmode/values_u_lens.ini
;%include inc_ini_nob2/values_nob2.ini


; 3x2pt without 2nd lens bin + DESI DR2 BAO
; LCDM
; Sum of neutrino masses fixed to 0.06 eV
; Nonlinear P(k) computed with baryonic feedback version of HMcode 2020
; NLA IA model w 2 params (amplitude and z power law)
; with baryonic feedback fixing T_AGN=7.7
; Gaussian priors on magnification using Y6 Balrog priors for DV 5.1
; nzmode redshift calibration
; Linear galaxy bias (default if no galbias noted)

[cosmological_parameters]
omega_m    	 = 	 0.1     0.319    0.6  
h0         	 = 	 0.58    0.67    0.80  
omega_b    	 = 	 0.03    0.049    0.07  
n_s        	 = 	 0.93    0.96    1.00  
A_s          = 2.1e-9
A_s_1e9      = 0.5 2.1 5.0
w          	 = 	 -1.0  
wa         	 = 	 0.0  
omega_k    	 = 	 0.0  
tau        	 = 	 0.054  
standard_neutrino_neff 	 = 	 3.044  
num_massive_neutrinos 	 = 	 3  
nnu        	 = 	 3.044  
mnu        	 = 	 0.06  

[bias_lens]
b1         	 = 	 0.8  1.54   3.0  
b2         	 = 	 1.81  
b3         	 = 	 0.8  1.85   3.0  
b4         	 = 	 0.8  1.76   3.0  
b5         	 = 	 0.8  1.93   3.0  
b6         	 = 	 0.8  1.90   3.0  

[shear_calibration_parameters]
m1_uncorr  	 = 	 -3.0  0.0  3.0  
m2_uncorr  	 = 	 -3.0  0.0  3.0  
m3_uncorr  	 = 	 -3.0  0.0  3.0  
m4_uncorr  	 = 	 -3.0  0.0  3.0  

[halo_model_parameters]
logt_agn   	 = 	 7.7  

[mag_alpha_lens]
alpha_1    	 = 	 -2. 1.58 6.  
alpha_2    	 = 	 -2. 1.38 6.  
alpha_3    	 = 	 -2. 2.04 6.  
alpha_4    	 = 	 -2. 2.21 6.  
alpha_5    	 = 	 -2. 2.45 6.  
alpha_6    	 = 	 -2. 2.42 6.  

[intrinsic_alignment_parameters]
z_piv      	 = 	 0.3  
a1         	 = 	 -5.0  1.0  5.0  
a2         	 = 	 0.0  
alpha1     	 = 	 -5.0 -1.0  5.0  
alpha2     	 = 	 0.0  
bias_ta    	 = 	 0.0  

[source_photoz_u]
u_0_uncorr 	 = 	 -3.0 0.0 3.0  
u_1_uncorr 	 = 	 -3.0 0.0 3.0  
u_2_uncorr 	 = 	 -3.0 0.0 3.0  
u_3_uncorr 	 = 	 -3.0 0.0 3.0  
u_4_uncorr 	 = 	 -3.0 0.0 3.0  
u_5_uncorr 	 = 	 -3.0 0.0 3.0  
u_6_uncorr 	 = 	 -3.0 0.0 3.0  

[lens_photoz_u]
u_0_0      	 = 	 -3.0 0.0 3.0  
u_0_1      	 = 	 -3.0 0.0 3.0  
u_0_2      	 = 	 -3.0 0.0 3.0  
u_1_0      	 = 	 0.0  
u_1_1      	 = 	 0.0  
u_1_2      	 = 	 0.0  
u_2_0      	 = 	 -3.0 0.0 3.0  
u_2_1      	 = 	 -3.0 0.0 3.0  
u_2_2      	 = 	 -3.0 0.0 3.0  
u_3_0      	 = 	 -3.0 0.0 3.0  
u_3_1      	 = 	 -3.0 0.0 3.0  
u_3_2      	 = 	 -3.0 0.0 3.0  
u_4_0      	 = 	 -3.0 0.0 3.0  
u_4_1      	 = 	 -3.0 0.0 3.0  
u_4_2      	 = 	 -3.0 0.0 3.0  
u_5_0      	 = 	 -3.0 0.0 3.0  
u_5_1      	 = 	 -3.0 0.0 3.0  
u_5_2      	 = 	 -3.0 0.0 3.0  

